<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript" src="<?php echo $this->getCollectorUrl() ?>"></script>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
	$('co-payment-form').insert('<?php echo $this->getField() ?>');
	$('co-payment-form').insert('<?php echo $this->getMappingField() ?>');
	Review.prototype.save = function() {
		try {
			<?php echo $this->getCall() ?>
		} catch(error) {
		}
		if (checkout.loadWaiting!=false) return;
		checkout.setLoadWaiting('review');
		Form.enable(payment.form);
		var params = Form.serialize(payment.form);
		if (this.agreementsForm) {
			params += '&'+Form.serialize(this.agreementsForm);
		}
		params.save = true;
		var request = new Ajax.Request(
		this.saveUrl,
		{
			method:'post',
			parameters:params,
			onComplete: this.onComplete,
			onSuccess: this.onSave,
			onFailure: checkout.ajaxFailure.bind(checkout)
		}
		);
	}
});
//]]
</script>
