<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $paymentNotice = $this->getEbcPaymentNotice(); ?>
<?php if($paymentNotice):?>
<div class="notification-global">
	<strong><?php echo $this->helper('eb2cpayment')->__('Payment methods need to be configured:') ?></strong>
	<?php echo implode(', ', $paymentNotice)?>.
	<?php echo $this->helper('eb2cpayment')->__('Click here to go to <a href="%s">Payment Method Configuration Section</a> and configured payment method settings.', $this->getPaymentSectionConfigurationUrl());?>
</div>
<?php endif;?>
