<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_cards  = $this->getGiftCards();
?>
<?php if ($_cards):?>
<?php foreach ($_cards as $_card): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card (%s)', $_card->getCode()); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_card->getAmount()) ?></td>
</tr>
<?php endforeach; ?>
<?php elseif ($_source->getGiftCardsAmount()>0): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_source->getGiftCardsAmount()) ?></td>
</tr>
<?php endif?>
