<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Order_Block_Order_Cancel */ ?>
<?php
	$_order = $this->getOrder();
	$_order_id = $_order->getRealOrderId();
	$_helper = $this->getHelper($this->getHelperClass());
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
	<h1><?php echo$_helper->__('Order #') . ' ' . $_order->getRealOrderId() . ' ' . $_helper->__($_order->getStatus()) ?></h1>
</div>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="order-cancel-form-validate">
	<input type="hidden" name="cancel_action" value="true"/>
	<input type="hidden" name="order_id" value="<?php echo $_order_id; ?>"/>
	<div class="fieldset">
		<h2 class="legend"><?php echo $this->__($this->getTextMessage()) ?></h2>
		<ul class="form-list">
			<li class="fields">
				<div class="field">
					<label for="cancel_reason" class="required"><em>*</em><?php echo $this->__('Reason') ?></label>
					<div class="input-box">
						<?php echo $this->getCancelReasonHtmlSelect() ?>
					</div>
				</div>
			</li>
		</ul>
	</div>
	<div class="buttons-set">
		<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
		<button type="submit" title="<?php echo $this->getCancelOrderButton() ?>" class="button"><span><span><?php echo $this->getCancelOrderButton() ?></span></span></button>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('order-cancel-form-validate', true);
//]]>
</script>
