<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Order_Overrides_Block_Order_Info */ ?>
<?php $order = $this->getOrder(); ?>
<?php $helper = $this->getHelper($this->getHelperClass()); ?>
<?php $links = $this->getLinks(); ?>
<?php $billingAddress = $order->getBillingAddress(); ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $helper->__('Order #') . ' ' . $order->getRealOrderId() . ' ' . $helper->__($order->getStatus()) ?></h1>
    <?php if ($order->getIsCancellable()) : ?>
        <a href="<?php echo $this->getCancelUrl($order->getRealOrderId()); ?>"><?php echo $helper->__('Cancel') ?></a>
    <?php endif ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($order) ?>
<dl class="order-info">
    <dt><?php echo $helper->__('About This Order:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
        <?php foreach ($links as $link): ?>
            <?php if($link->getUrl()): ?>
                <li><a href="<?php echo $link->getUrl() ?>"><?php echo $link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $helper->__('Order Date: ') . $this->formatDate($order->getCreatedAt(), 'long'); ?></p>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $helper->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <?php if ($billingAddress): ?>
                    <?php $phone = $billingAddress->getPhone(); ?>
                    <address>
                        <?php echo $billingAddress->getFirstname() . ' ' . $billingAddress->getLastname(); ?><br />
                        <?php echo $billingAddress->getStreet1(); ?><br />
                        <?php echo $billingAddress->getCity() . ', ' . $billingAddress->getMainDivision() . ' ' .  $billingAddress->getPostalCode(); ?><br />
                        <?php echo $billingAddress->getCountryCode(); ?><br />
                        <?php if ($phone): ?>
                            <?php echo $this->__('T') . ':' . $phone; ?><br />
                        <?php endif; ?>
                    </address>
                <?php else: ?>
                    <p>
                        <?php echo $helper->__('A billing address was not found for this order. Please contact customer service for more information.'); ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $helper->__('Payment Method(s)') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
