<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Order_Overrides_Block_Order_Items */ ?>
<?php
/** @var EbayEnterprise_Order_Helper_Data */
$_helper = $this->getHelper($this->getHelperClass());
/** @var EbayEnterprise_Order_Model_Detail_Process_Response_Shipgroup */
$_shipGroup = $this->getShipGroup();
?>
<table class="data-table" id="my-orders-table" summary="<?php echo $_helper->__('Items Ordered') ?>">
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<thead>
		<tr>
			<th><?php echo $_helper->__('Product Name') ?></th>
			<th><?php echo $_helper->__('SKU') ?></th>
			<th class="a-right"><?php echo $_helper->__('Price') ?></th>
			<th class="a-center"><?php echo $_helper->__('Qty') ?></th>
			<th class="a-right"><?php echo $_helper->__('Subtotal') ?></th>
		</tr>
	</thead>
	<?php $_items = $_shipGroup->getItemsCollection(); ?>
	<tbody>
		<?php foreach ($_items as $_item): ?>
		<tr>
			<td><?php echo $_item->getName(); ?></td>
			<td><?php echo $_item->getSku(); ?></td>
			<td class="a-right"><?php echo $this->formatPrice($_item->getPrice()); ?></td>
			<td class="a-right">
				<span class="nobr">
				<?php echo $this->__('Ordered'); ?>: <strong><?php echo $_item->getQtyOrdered(); ?></strong><br />
				<?php $_qtyShipped = $_item->getQtyShipped(); if ($_qtyShipped > 0): ?>
					<?php echo $this->__('Shipped'); ?>: <strong><?php echo $_qtyShipped; ?></strong><br />
				<?php endif; ?>
				</span>
			</td>
			<td class="a-right"><?php echo $this->formatPrice($_item->getRowTotal()); ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	<tfoot>
		<tr>
			<td class="a-right" colspan="4"><?php echo $_helper->__('Subtotal')?></td>
			<td class="a-right"><?php echo $this->formatPrice($_shipGroup->getSubtotal()); ?></td>
		</tr>
		<?php $_shippingAmount = $_shipGroup->getShippingAmount(); if ($_shippingAmount > 0): ?>
		<tr>
			<td class="a-right" colspan="4"><?php echo $_helper->__('Shipping and Handling')?></td>
			<td class="a-right"><?php echo $this->formatPrice($_shippingAmount); ?></td>
		</tr>
		<?php endif; ?>
		<?php $_discountAmount = $_shipGroup->getDiscountAmount(); if ($_discountAmount > 0): ?>
		<tr>
			<td class="a-right" colspan="4"><?php echo $_helper->__('Discounts')?></td>
			<td class="a-right"><?php echo $this->formatPrice($_discountAmount); ?></td>
		</tr>
		<?php endif; ?>
		<?php $_taxAmount = $_shipGroup->getTaxAmount(); if ($_taxAmount > 0): ?>
		<tr>
			<td class="a-right" colspan="4"><?php echo $_helper->__('Tax')?></td>
			<td class="a-right"><?php echo $this->formatPrice($_taxAmount); ?></td>
		</tr>
		<?php endif; ?>
		<tr class="grand_total last">
			<td class="a-right" colspan="4"><strong><?php echo $_helper->__('Grand Total')?></strong></td>
			<td class="last a-right"><strong><?php echo $this->formatPrice($_shipGroup->getOrderTotal()); ?></strong></td>
		</tr>
	</tfoot>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
