<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright	Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Order_Overrides_Block_Order_View */ ?>
<?php
	$_helper = $this->getHelper($this->getHelperClass());
	$_order = $this->getOrder();
	$_shipGroups = $_order->getShipGroupsCollection();
	$_shipGroupNumber = 1;
	$_shipGroupTotal = $_shipGroups->getSize();
?>
<?php foreach ($_shipGroups as $_shipGroup): ?>
	<?php if (!$_order->getIsVirtual()): ?>
		<div class="order-items order-details">
			<h2 class="table-caption"><?php echo $this->__("Ship Group #{$_shipGroupNumber}") ?></h2>
		</div>
		<div class="col2-set order-info-box">
			<div class="col-1">
				<div class="box">
					<div class="box-title">
						<h2><?php echo $_helper->__('Shipping Address') ?></h2>
					</div>
					<div class="box-content">
						<address>
							<?php $_sa = $_shipGroup->getShippingAddress(); ?>
							<?php echo $_sa->getFirstname() . ' ' . $_sa->getLastname(); ?><br />
							<?php if ($_sa->getIsVirtualAddress()): ?>
								<?php echo $_sa->getEmail(); ?><br />
							<?php else: ?>
								<?php echo $_sa->getStreet1(); ?><br />
								<?php echo $_sa->getCity() . ', ' . $_sa->getMainDivision() . ' ' .  $_sa->getPostalCode(); ?><br />
								<?php echo $_sa->getCountryCode(); ?><br />
								<?php $_phone = $_sa->getPhone(); if ($_phone): ?>
									<?php echo $this->__('T'); ?>: <?php echo $_phone; ?><br />
								<?php endif; ?>
							<?php endif; ?>
						</address>
					</div>
				</div>
			</div>
			<div class="col-2">
				<div class="box">
					<div class="box-title">
						<h2><?php echo $_helper->__('Shipping Method') ?></h2>
					</div>
					<div class="box-content">
						<?php $_shippingMethod = $_shipGroup->getShippingDescription(); ?>
						<?php if ($_shippingMethod): ?>
							<?php echo $this->escapeHtml($_shippingMethod) ?>
						<?php else: ?>
							<p><?php echo $_helper->__('No shipping information available'); ?></p>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>
	<div class="order-items order-details">
		<h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
				<?php if ($_order->getTracksCollection()->count()) : ?>
					<span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?>"><?php echo $this->__('Track your order') ?></a>
				<?php endif; ?>
		</h2>
		<?php $this->getChild('order_items')->setData('ship_group', $_shipGroup); ?>
		<?php
			// The second parameter value false is essential here because the method
			// Mage_Core_Block_Abstract::getChildHtml() will cache the previous child HTML
			// which will result in duplicate order items.
			echo $this->getChildHtml('order_items', false);
		?>
	</div>
	<?php $_shipGroupNumber++; ?>
	<?php if ($_shipGroupNumber < $_shipGroupTotal): ?>
		<div class="order-items order-details"><br /><br /></div>
	<?php endif; ?>
<?php endforeach; ?>
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
</div>
