language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
before_install:
    - composer self-update
    - mysql -e 'create database IF NOT EXISTS circle_test;' -uroot
    - mysql -e 'grant all on circle_test.* to ubuntu;' -uroot
install:
    - circle-ci/magento-install
    - mkdir ../build && rsync -a ../magento/ ../build
    - circle-ci/setup
dependencies:
script: cd ../build && phpunit
sudo: false # Containerize build
