#!/usr/bin/env bash

##
# Source this file to get utilities that make
# development commands easier.

##
# Open the default web browser to the current
# host:port for the webapp container.
#
# Usage: browse
#    or: browse 45-mg01-bkgr-0.html
browse() {
    compose ps -q |
        xargs -n1 -I{} docker port {} 80 2>/dev/null |
        sed "s/0.0.0.0/$(docker-machine ip "$DOCKER_MACHINE_NAME")/" |
        xargs -n1 -I{} open "http://{}/$1"
}

##
# Because `docker-compose` is too long.
compose () { 
    docker-compose "$@"
}

##
# Because `docker-compose run --rm` is too long.
compost () { 
    compose run --rm "$@"
}
