#!/bin/bash -xe

main() {
    local magento_version="${1:- 1.9.1.0}"
    if [[ $1 = bash ]]; then
        shift
        exec bash "$@"
    fi
    makedirs
    fetch_unpack_magento "$magento_version"
    install_magento
    copy_testkit
}

makedirs() {
    mkdir -p build/magetars build/magento build/doc build/pdepend build/phpmd build/phpunit
}

fetch_unpack_magento() (
    local magento_version="${1:- 1.9.1.0}"
    local magento_urls=(
        "http://clean.mage.gspt.net/pkgs/magento-${magento_version}.tar.xz"
        "http://www.magentocommerce.com/downloads/assets/${magento_version}/magento-${magento_version}.tar.bz2"
    )
    local magento_tarballs=("${magento_urls[@]##*/}")
    local url
    local file
    local file_found=0
    cd build/magetars
    for file in "${magento_tarballs[@]}"; do
        if [[ -f "$file" ]]; then
            file_found=1
            break
        fi
    done
    if (( ! file_found )); then
        for url in "${magento_urls[@]}"; do
            # Magento site doesn't support resuming downloads.
            if curl -f -#O "$url"; then
                file="${url##*/}"
                break
            fi
        done
    fi
    cd ../magento
    [[ -f app/etc/local.xml ]] || tar --strip-components=1 -xf "../magetars/${file}"
)

install_magento() (
    cd build/magento
    if [[ ! -f app/etc/local.xml ]]; then
        php install.php \
            --admin_email admin@example.com \
            --admin_firstname ad \
            --admin_lastname min \
            --admin_password testing123 \
            --admin_username admin \
            --db_host db_1 \
            --db_name "$DB_1_ENV_MYSQL_DATABASE" \
            --db_pass "$DB_1_ENV_MYSQL_PASSWORD" \
            --db_user "$DB_1_ENV_MYSQL_USER" \
            --default_currency USD \
            --license_agreement_accepted yes \
            --locale en_US \
            --secure_base_url "http://${MAGENTO_HOST-example.com}/" \
            --skip_url_validation yes \
            --timezone America/New_York \
            --url "http://${MAGENTO_HOST-example.com}/" \
            --use_rewrites yes \
            --use_secure no \
            --use_secure_admin no
    fi
    chown -R :www-data media var
    chmod -R g+sw media var
    if [[ ! $MAGENTO_HOST ]]; then
        # No base url was specified, so disable redirecting to base url.
        mysql -h db_1 -u "$DB_1_ENV_MYSQL_USER" --password="${DB_1_ENV_MYSQL_PASSWORD}" "$DB_1_ENV_MYSQL_DATABASE" -e 'DELETE FROM core_config_data WHERE path LIKE "web/%secure/base_url"\g'
        n98-magerun cache:disable config
    fi
)

copy_testkit() {
    cp tests/composer.xml build/magento/app/etc/
    cp tests/local.xml.phpunit.docker build/magento/app/etc/local.xml.phpunit
    cp tests/phpunit.xml.dist build/magento/
    cp tests/composer.docker.json build/magento/composer.json
}

main "$@"
