<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var EbayEnterprise_Amqp_Block_System_Config_Testamqpconnection $this */
?>
<button class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
	<span id="message_queue_response_message"><?php echo $this->getButtonLabel() ?></span>
</button>
<script type="text/javascript">
	(function () {
		var buttonElemId = '<?php echo $this->getHtmlId() ?>';
		var url = '<?php echo $this->getAjaxUrl() ?>';
		window.addAmqpTestButtonObserver(buttonElemId, url);
	})();
</script>
