<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * When suggestions are available from EB2C for the current address, render
 * the suggestions and necessary form fields for suggestions to be chosen.
 */
if ($this->shouldShowSuggestions()): ?>
<fieldset class="suggestion-fields" id="address-validation-suggestions">
	<p class="validation-message top-message"><?php echo $this->getSuggestedAddressMessage() ?></p>
	<ul class="suggestion-list">
		<?php foreach ($this->getSuggestedAddresses() as $idx => $suggestion): ?>
		<li class="suggestion">
			<label>
				<input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $suggestion->getStashKey() ?>" id="suggestion-<?php echo $idx ?>" data-address-data='<?php echo $this->getAddressJsonData($suggestion) ?>' />
				<?php echo $this->getSuggestionLabel() ?>
			</label>
			<p class="address"><?php echo $this->getRenderedAddress($suggestion) ?></p>
		</li>
		<?php endforeach; ?>
		<?php $_originalAddress = $this->getOriginalAddress() ?>
		<li class="suggestion original">
			<label>
				<input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $_originalAddress->getStashKey() ?>" id="suggestion-original" data-address-data='<?php echo $this->getAddressJsonData($_originalAddress) ?>' />
				<?php echo $this->getOriginalAddressLabel() ?>
			</label>
			<p class="address"><?php echo $this->getRenderedAddress($_originalAddress) ?></p>
		</li>
		<li class="suggestion new">
			<label class="validation-message new-address-message">
				<input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $this->getNewAddressSelectionValue() ?>" id="suggestion-new" data-address-data='<?php echo $this->getAddressJsonData($_originalAddress) ?>' />
				<?php echo $this->getNewAddressLabel() ?>
			</label>
		</li>
	</ul>
</fieldset>
<?php endif; ?>
