<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * Add new JS to do specific giftcard functionality
 */
?>
<script type="text/javascript">
	//<![CDATA[
	var giftcardForm = new varienForm('edit_form');
	function checkGiftCardStatus()
	{
		new Ajax.Updater(
			'giftcard_balance_lookup',
			'<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
			{
				onCreate: function() { $('gc-please-wait').show(); },
				onComplete: function() { $('gc-please-wait').hide(); },
				parameters : {giftcard_code : $('giftcard_code').value, giftcard_pin : $('giftcard_pin').value}
			}
		);
	}

	function addGiftCard() {
		var code = $('giftcard_code').value;
		var pin = $('giftcard_pin').value;
		var data = {};
		data['giftcard_add'] = code;
		data['giftcard_pan'] = code;
		data['giftcard_pin'] = pin;
		order.loadArea(['totals', 'billing_method', 'items'], true, data);
	}

	function removeGiftCard(code) {
		var data = {};
		data['giftcard_remove'] = code;
		order.loadArea(['totals', 'billing_method', 'items'], true, data);
	}
	//]]>
</script>
