<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Note: This mark is a requirement of PayPal
 *
 * @see EbayEnterprise_Paypal_Block_Standard_Form
 */
?>
<!-- PayPal Logo -->
<img src="<?php echo $this->escapeHtml($this->getPaymentMarkImageUrl()) ?>"
	alt="<?php echo $this->getPaymentMarkAltText() ?>"
	class="v-middle"/>&nbsp;
<a href="<?php echo $this->getWhatIsPaypalUrl() ?>"
	onclick="javascript:window.open('<?php echo $this->getWhatIsPaypalUrl() ?>','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, left=0, top=0, width=400, height=350'); return false;">
	<?php echo Mage::helper('ebayenterprise_paypal')->__('What is PayPal?'); ?>
</a>
<!-- PayPal Logo -->
