#!/usr/bin/env python

import json
from os.path import basename
import requests
import sys
from subprocess import Popen, PIPE
from datetime import datetime as dt

api_endpoint = 'https://github.scm.corp.ebay.com/api/v3'

def create_header_with_auth(auth_token):
	return {
		'Accept': 'application/vnd.github.v3+json',
		'Authorization': 'token {key}'.format(key=auth_token),
	}

def create_tag(repo, version, auth_headers):
	"""
	Create a tag object and annotated tag reference for the new release.
	"""
	sha = Popen(["git", "show-ref", "-s", "HEAD"], stdout=PIPE).communicate()[0]
	tag_obj_data = {
		"tag": version,
		"message": "Version {version}".format(version=version),
		"object": sha,
		"type": "commit",
		"tagger": {
			"name": "Jenkins",
			"email": "msmith3@ebay.com",
			"date": dt.isoformat(dt.now().replace(microsecond=0))
		},
	}
	# If you only create the tag without the object
	# it creates a lightweight tag. We want an annotated one.
	tag_data = {
		"ref": "refs/tags/{tag}".format(tag=version),
		"sha": sha,
	}
	headers = dict(auth_headers.items() + {'Content-Type': 'application/json',}.items())
	requests.post(
		"{endpoint}/repos/{repo}/git/tags".format(endpoint=api_endpoint,repo=repo),
		data=json.dumps(tag_obj_data),
		headers=headers,
	).raise_for_status()
	requests.post(
		"{endpoint}/repos/{repo}/git/refs".format(endpoint=api_endpoint,repo=repo),
		data=json.dumps(tag_data),
		headers=headers,
	).raise_for_status()

def create_release(repo, version, auth_headers):
	"""
	Create a new release and return the id of the new release.
	"""
	# For now, manually create the annotated tag and push that
	# because github releases seems to create lightweight tags
	# by default.
	create_tag(repo,version,auth_headers)
	release_data = {
		'tag_name': version,
		'target_commitish': 'master',
		'name': version,
		'body': version,
		'draft': False,
		'prerelease': False,
	}
	headers = dict(auth_headers.items() + {'Content-Type': 'application/json',}.items())
	r = requests.post(
		'{endpoint}/repos/{repo}/releases'.format(endpoint=api_endpoint,repo=repo),
		data=json.dumps(release_data),
		headers=headers
	)
	r.raise_for_status()
	return r.json()['id']

def upload_github(repo, release_id, archive, auth_headers):
	"""
	Upload the release archive as an asset to a relase.
	eBay Github can't currently do this so will not work.
	"""
	headers = dict(auth_headers.items() + {'Content-Type': 'application/x-gzip',}.items())
	files = {'file': open(archive, 'rb')}
	url = '{endpoint}/repos/{repo}/releases/{release}/assets'.format(endpoint=api_endpoint, repo=repo, release=release_id)
	r = requests.post(
		url,
		params={'name': basename(archive)},
		headers=headers,
		files=files
	)
	r.raise_for_status()
	return r.status_code

def main(version, module_archive, build_repo, github_key, *argv):
	"""
	Create a new release of the project on Github and...that all for now.
	"""
	auth_headers = create_header_with_auth(github_key)
	try:
		create_release(build_repo, version, auth_headers)
	except Exception, e:
		print "Unable to create new release"
		print e
		return 1
	print "Created new release for version {v}".format(v=version)
	return 0


if __name__ == '__main__':
	sys.exit(main(*sys.argv[1:]))
