<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="checkout-onepage-payment-additional-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo Mage::helper('enterprise_giftcardaccount')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('core')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>
</p>
</div>
