<?php
/**
 * @category   TrueAction
 * @package    TrueAction_Eb2c
 * @copyright  Copyright (c) 2013 True Action Network (http://www.trueaction.com)
 */
?>
<div class="page-title">
	<h1><?php echo $this->__('Edit Stored Value Account Data') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('eb2cstoredvalue/account/save') ?>" method="post" id="form-validate">
	<div class="fieldset">
	<?php echo $this->getBlockHtml('formkey')?>
		<h2 class="legend"><?php echo $this->__('Stored Value Account Data') ?></h2>
		<ul class="form-list">
			<li>
				<div class="input-box">
					<label for="eb2c_sv_pan"><?php echo $this->__('Payment Account Numbers') ?></label><br />
					<input type="text" id="eb2c_sv_pan" name="account_sv" title="<?php echo $this->__('Payment Account Numbers') ?>" class="input-text required-entry validate-number validate-storedvalue-sv" value="<?php echo $this->getAccountPan() ?>" onchange="svCheck.checkSV(this); return false;" />
				</div>
			</li>
			<li>
				<div class="input-box">
					<label for="eb2c_sv_pin"><?php echo $this->__('Personal Identification Number') ?></label><br />
					<input type="text" id="eb2c_sv_pin" name="account_name" title="<?php echo $this->__('Personal Identification Number') ?>" class="input-text required-entry" value="<?php echo $this->getAccountPin() ?>" />
				</div>
			</li>
		</ul>
	</div>
	<div class="buttons-set">
		<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		<p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
		<button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
	</div>
</form>

<script type="text/javascript">
//<![CDATA[
	svCheck = new svAjaxCheck('<?php echo $this->getUrl('eb2cstoredvalue/ajax/checkSV');?>','1');
	var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
