<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Eb2cOrder_Overrides_Block_Order_Items */ ?>
<?php
/** @var Mage_Sales_Model_Order */
$_order = $this->getOrder();
/** @var EbayEnterprise_Eb2cOrder_Helper_Data */
$_helper = $this->getHelper();
?>
<table class="data-table" id="my-orders-table" summary="<?php echo $this->getHelper()->__('Items Ordered') ?>">
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<col width="1" />
	<thead>
		<tr>
			<th><?php echo $_helper->__('Product Name') ?></th>
			<th><?php echo $_helper->__('SKU') ?></th>
			<th class="a-right"><?php echo $_helper->__('Price') ?></th>
			<th class="a-center"><?php echo $_helper->__('Qty') ?></th>
			<th class="a-right"><?php echo $_helper->__('Subtotal') ?></th>
		</tr>
	</thead>
	<tfoot>
			<!-- Totals child html was here in original. -->
	</tfoot>
		<?php $_items = $_order->getItemsCollection(); ?>
		<tbody>
			<?php foreach ($_items as $_item): ?>
			<tr>
				<td><?php echo $_item->getName(); ?></td>
				<td><?php echo $_item->getSku(); ?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_item->getPrice()); ?></td>
				<td class="a-center"><?php echo $_item->getQtyOrdered(); ?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_item->getRowTotal()); ?></td>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td class="a-right" colspan="4"><?php echo $_helper->__('Subtotal')?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_order->getSubtotal()); ?></td>
			</tr>
			<tr>
				<td class="a-right" colspan="4"><?php echo $_helper->__('Shipping and Handling')?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_order->getShippingAmount())?></td>
			</tr>
			<tr>
				<td class="a-right" colspan="4"><?php echo $_helper->__('Discounts')?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_order->getDiscountAmount()); ?></td>
			</tr>
			<tr>
				<td class="a-right" colspan="4"><?php echo $_helper->__('Tax')?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($_order->getTaxAmount()); ?></td>
			</tr>
			<tr>
				<td class="a-right" colspan="4"><?php echo $_helper->__('Total')?></td>
				<td class="a-right"><?php echo $_helper->formatPrice($this->getOrderTotal()); ?></td>
			</tr>
		</tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
