<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license	 http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Eb2cOrder_Overrides_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
	<h1><?php echo $this->getHelper()->__('Order #') . ' ' . $_order->getCustomerOrderId() . ' ' . $this->getHelper()->__($_order->getStatusLabel()) ?></h1>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
	<dt><?php echo $this->getHelper()->__('About This Order:') ?></dt>
	<dd>
		<?php $_links = $this->getLinks(); ?>
		<ul id="order-info-tabs">
		<?php foreach ($_links as $_link): ?>
			<?php if($_link->getUrl()): ?>
				<li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
			<?php else: ?>
				<li class="current"><?php echo $_link->getLabel() ?></li>
			<?php endif; ?>
		<?php endforeach; ?>
		</ul>
		<script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
	</dd>
</dl>
<p class="order-date"><?php echo $this->getHelper()->__('Order Date: ') . $this->formatDate($_order->getOrderDate(), 'long'); ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
	<div class="col-1">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->getHelper()->__('Shipping Address') ?></h2>
			</div>
			<div class="box-content">
				<address>
					<?php $_sa = $_order->getShippingAddress(); ?>
					<?php echo $_sa->getFirstname() . ' ' . $_sa->getLastname(); ?><br />
					<?php echo $_sa->getStreet1(); ?><br />
					<?php echo $_sa->getCity() . ', ' . $_sa->getMainDivision() . ' ' .  $_sa->getPostalCode(); ?><br />
					<?php echo $_sa->getCountryCode(); ?><br />
				</address>
			</div>
		</div>
	</div>
	<div class="col-2">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->getHelper()->__('Shipping Method') ?></h2>
			</div>
			<div class="box-content">
				<?php if ($_order->getShippingDescription()): ?>
					<?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
				<?php else: ?>
					<p><?php echo $this->getHelper()->__('No shipping information available'); ?></p>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
	<div class="col-1">
		<div class="box">
			<div class="box-title">
				<h2><?php echo $this->getHelper()->__('Billing Address') ?></h2>
			</div>
			<div class="box-content">
				<address>
					<?php $_ba = $_order->getBillingAddress(); ?>
					<?php echo $_ba->getFirstname() . ' ' . $_ba->getLastname(); ?><br />
					<?php echo $_ba->getStreet1(); ?><br />
					<?php echo $_ba->getCity() . ', ' . $_ba->getMainDivision() . ' ' .  $_ba->getPostalCode(); ?><br />
					<?php echo $_ba->getCountryCode(); ?><br />
				</address>
			</div>
		</div>
	</div>
	<div class="col-2">
		<div class="box box-payment">
			<div class="box-title">
				<h2><?php echo $this->getHelper()->__('Payment Method(s)') ?></h2>
			</div>
			<div class="box-content">
				<?php $_payments = $_order->getPaymentsCollection(); ?>
				<?php foreach ($_payments as $_payment): ?>
					<?php echo trim($_payment->getPaymentTypeName()); ?> (<?php echo $_payment->getTenderType(); ?>)<br />
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

