<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright	Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license	 http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Eb2cOrder_Overrides_Block_Order_View */ ?>
<div class="order-items order-details">
	 <?php $_order = $this->getOrder() ?>
	 <h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
			<?php if ($_order->getTracksCollection()->count()) : ?>
				<span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?>"><?php echo $this->__('Track your order') ?></a>
			<?php endif; ?>
	 </h2>
	 <?php echo $this->getChildHtml('order_items') ?>
	<!-- @TODO: Gift Messages? Check XSD -->
	 <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
	 <?php if (count($_history)): ?>
	 <div class="order-additional order-comments">
			<h2 class="sub-title"><?php echo $this->__('About Your Order') ?></h2>
			<dl class="order-about">
				<?php foreach ($_history as $_historyItem): ?>
					 <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
					 <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
				<?php endforeach; ?>
			</dl>
		</div>
		<?php endif; ?>
		<div class="buttons-set">
			<p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
		</div>
</div>

