<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license	 http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="box-account box-recent">
<?php $_ordersShown = 0; ?>
<?php $_orders = $this->getOrders(); ?>
	<div class="box-head">
		<h2><?php
echo $this->getHelper()->__('Recent Orders');
?>
		</h2>
		<?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->getHelper()->__('View All') ?></a><?php endif; ?>
	</div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
	<table class="data-table orders" id="my-orders-table">
	<col width="1" />
	<col width="1" />
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" />
		<thead>
			<tr>
				<th class="number"><?php echo $this->getHelper()->__('Order #') ?></th>
				<th class="date"><?php echo $this->getHelper()->__('Date') ?></th>
				<th class="total"><span class="nobr"><?php echo $this->getHelper()->__('Order Total') ?></span></th>
				<th class="status"><?php echo $this->getHelper()->__('Status') ?></th>
				<th class="view">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($_orders as $_order): ?>
				<tr>
					<td class="number"><?php echo $_order->getCustomerOrderId() ?></td>
					<td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getOrderDate()) ?></span></td>
					<td class="total"><?php echo $this->getHelper()->formatPrice($_order->getGrandTotal()) ?></td>
					<td class="status"><em><?php echo $_order->getStatus() ?></em></td>
					<td class="a-center view">
						<span class="nobr">
							<a href="<?php echo $this->getViewUrl($_order->getCustomerOrderId()); ?>"><?php echo $this->getHelper()->__('View Order') ?></a>
						</span>
					</td>
				</tr>
				<?php if (++$_ordersShown >= $this->getMaxOrdersToShow()): ?>
				<?php break; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
	<p><?php echo $this->getHelper()->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
