<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<div class="giftcard-status">
    <div class="page-title">
        <h1><?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card status'); ?></h1>
    </div>

<?php if ($this->getCode()): ?>
    <?php echo $this->getChildHtml('check_result') ?>
<?php endif; ?>
    <form method="post" id="codeForm">
        <fieldset>
            <ul class="form-list">
                <li>
                    <label for="code"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Enter Gift Card code'); ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" name="giftcard_code" id="code" value="<?php echo $this->escapeHtml($this->getCode()) ?>" />
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set form-buttons btn-only">
             <button class="button" type="button" onclick="cForm.submit()"><span><span><?php echo Mage::helper('enterprise_giftcardaccount')->__('Check'); ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    var cForm = new VarienForm('codeForm');
    </script>
</div>
