<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @see EbayEnterprise_GiftCard_Block_Adminhtml_Sales_Order_Create_Payment
 * overriding giftcardaccount payment block in order to add pan and pin field and do gift card balance check
 */
?>
<div class="entry-edit ebay-enterprise-giftcard box-right">
	<div class="entry-edit-head">
		<h4 class="icon-head"><?php echo $this->__('Gift Cards'); ?></h4>
	</div>
	<fieldset class="np">
		<div id="ebay_enterprise_giftcard_balance_lookup"></div>
		<span id="ebay-enterprise-giftcard-please-wait" class="please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
		</span>
		<div class="content">
			<ul class="form-list">
				<li>
					<label style="text-align:left; display: block; margin: 0 0 7px; padding: 2px 15px 0 0;font-weight: bold;" for="ebay_enterprise_giftcard_code"><em class="required" style="margin-right: 4px;">*</em>
					<?php echo $this->__('Card Number') ?></label>
					<input style="width: 280px;" class="" id="ebay_enterprise_giftcard_code" name="ebay_enterprise_giftcard_code" value="" />
				</li>
				<li>
					<label style="text-align:left; display: block;margin: 0 0 7px; padding: 2px 15px 0 0;font-weight: bold;" for="ebay_enterprise_giftcard_pin"><em class="required" style="margin-right: 4px;">*</em>
					<?php echo $this->__('Personal Identification Number (PIN)') ?></label>
					<input style="width: 280px;" class="" id="ebay_enterprise_giftcard_pin" name="ebay_enterprise_giftcard_pin" value="" />
				</li>
			</ul>
			<div class="buttons-set">
				<button class="button" onclick="addEbayEnterpriseGiftCard()" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
			<button class="button check-gc-status" onclick="checkEbayEnterpriseGiftCardStatus();" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button>
			</div>

			<?php foreach ($this->getGiftCards() as $_card): ?>
				<p><strong><?php echo $_card->getCardNumber(); ?></strong> <strong><?php echo $this->_formatPrice($_card->getAmountToRedeem()); ?></strong> [<a href="#" onclick="removeEbayEnterpriseGiftCard('<?php echo $_card->getCardNumber(); ?>'); return false;" title="<?php echo $this->__('Remove'); ?>"><?php echo $this->__('Remove'); ?></a>]</p>
			<?php endforeach; ?>
		</div>
	</fieldset>
</div>
