<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this EbayEnterprise_PayPal_Block_Express_Review */
?>
<fieldset id="shipping-method-container">
	<?php if ($this->getCanEditShippingMethod()
		|| !$this->getCurrentShippingRate()
	): ?>
		<?php if ($groups = $this->getShippingRateGroups()): ?>
			<?php $currentRate = $this->getCurrentShippingRate(); ?>
			<select name="shipping_method" id="shipping_method"
			        style="width:250px;" class="required-entry">
				<?php if (!$currentRate): ?>
					<option value=""><?php echo $this->__(
							'Please select a shipping method...'
						) ?></option>
				<?php endif; ?>
				<?php foreach ($groups as $code => $rates): ?>
					<optgroup label="<?php echo $this->escapeHtml(
						$this->getCarrierName($code)
					) ?>" style="font-style:normal;">
						<?php foreach ($rates as $rate): ?>
							<option
								value="<?php echo $this->renderShippingRateValue(
									$rate
								) ?>"<?php echo ($currentRate === $rate)
								? ' selected="selected"' : ''; ?>>
								<?php echo $this->renderShippingRateOption(
									$rate
								) ?>
							</option>
						<?php endforeach; ?>
					</optgroup>
				<?php endforeach; ?>
			</select>
		<?php else: ?>
			<p><strong><?php echo $this->__(
						'Sorry, no quotes are available for this order at this time.'
					) ?></strong></p>
		<?php endif; ?>
	<?php else: ?>
		<p><strong><?php echo $this->renderShippingRateOption(
					$this->getCurrentShippingRate()
				) ?></strong></p>
	<?php endif; ?>
</fieldset>
<div style="display:none" id="shipping_method_update"><p><?php echo $this->__(
			'Please update order data to get shipping methods and rates'
		) ?></p></div>
