<?php
/**
 * When suggestions are available from EB2C for the current address, render
 * the suggestions and necessary form fields for suggestions to be chosen.
 */
if ($this->shouldShowSuggestions()): ?>
<fieldset class="suggestion-fields" id="address-validation-suggestions">
	<p class="validation-message top-message"><?php echo $this->getSuggestedAddressMessage() ?></p>
	<ul class="suggestion-list">
		<?php foreach ($this->getSuggestedAddresses() as $idx => $suggestion): ?>
		<li class="suggestion">
			<label for="suggestion-<?php echo $idx ?>">
				<input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $suggestion->getStashKey() ?>" id="suggestion-<?php echo $idx ?>" />
				<?php echo $this->getSuggestionLabel() ?>
			</label>
			<p class="address"><?php echo $this->getRenderedAddress($suggestion) ?></p>
		</li>
		<?php endforeach; ?>
		<?php $_originalAddress = $this->getOriginalAddress() ?>
		<li class="suggestion original">
			<label for="suggestion-original"><input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $_originalAddress->getStashKey() ?>" id="suggestion-original" />
				<?php echo $this->getOriginalAddressLabel() ?>
			</label>
			<p class="address"><?php echo $this->getRenderedAddress($_originalAddress) ?></p>
		</li>
		<li class="suggestion new">
			<label for="suggestion-new" class="validation-message new-address-message">
				<input type="radio" name="<?php echo $this->getSuggestionInputName() ?>" value="<?php echo $this->getNewAddressSelectionValue() ?>" id="suggestion-new" />
				<?php echo $this->getNewAddressLabel() ?>
			</label>
		</li>
	</ul>
</fieldset>
<?php endif; ?>
