<?php
class TrueAction_Eb2cCore_Model_Config extends TrueAction_Eb2cCore_Model_Config_Abstract
{
	protected $_configPaths = array(
		'api_hostname'                => 'eb2ccore/api/hostname',
		'api_key'                     => 'eb2ccore/api/key',
		'api_major_version'           => 'eb2ccore/api/major_version',
		'api_minor_version'           => 'eb2ccore/api/minor_version',
		'api_namespace'               => 'eb2ccore/api/xml_namespace',
		'api_timeout'                 => 'eb2ccore/api/timeout',
		'api_xsd_path'                => 'eb2ccore/api/xsd_path',
		'catalog_id'                  => 'eb2ccore/general/catalog_id',
		'client_customer_id_prefix'   => 'eb2ccore/general/client_customer_id_prefix',
		'client_id'                   => 'eb2ccore/general/client_id',
		'client_order_id_prefix'      => 'eb2ccore/general/client_order_id_prefix',
		'delete_remote_feed_files'    => 'eb2ccore/feed/delete_remote_feed_files',
		'feed_available_models'       => 'eb2ccore/feed/available_models',
		'feed_destination_type'       => 'eb2ccore/feed/destination_type',
		'feed_enabled_reindex'        => 'eb2ccore/feed/enabled_reindex',
		'feed_fetch_connect_attempts' => 'eb2ccore/feed/filetransfer_remote_connect_attempts',
		'feed_fetch_retry_timer'      => 'eb2ccore/feed/filetransfer_remote_retry_timer',
		'feed_ack_remote_path'        => 'eb2ccore/feed/acknowledgement/remote_path',
		'feed_ack_filename_pattern'   => 'eb2ccore/feed/acknowledgement/filename_pattern',
		'feed_ack_timestamp_format'   => 'eb2ccore/feed/acknowledgement/timestamp_format',
		'feed_ack_xsd'                => 'eb2ccore/feed/acknowledgement/xsd',
		'inventory_expiration_time'   => 'eb2ccore/service/inventory/expiration',
		'language_code'               =>  'eb2ccore/general/language_code',
		'service_order_timeout'       => 'eb2ccore/service/order/timeout',
		'service_payment_timeout'     => 'eb2ccore/service/payment/timeout',
		'sftp_auth_type'              => 'eb2ccore/feed/filetransfer_sftp_auth_type',
		'sftp_location'               => 'eb2ccore/feed/filetransfer_sftp_host',
		'sftp_password'               => 'eb2ccore/feed/filetransfer_sftp_password',
		'sftp_private_key'            => 'eb2ccore/feed/filetransfer_sftp_ssh_prv_key',
		'sftp_username'               => 'eb2ccore/feed/filetransfer_sftp_username',
		'store_id'                    => 'eb2ccore/general/store_id',
		'feed_header_template'        => 'eb2ccore/feed/header_template',
		'error_feed_file_pattern'     => 'eb2ccore/feed/error_confirmation_feed/file_pattern',
		'error_feed_remote_mailbox'   => 'eb2ccore/feed/error_confirmation_feed/remote_mailbox',
		'export_resend_time_limit'    => 'eb2ccore/feed/export/ack/resend_wait_time',
		'feed_send_directory'         => 'eb2ccore/feed/filetransfer_exports/product/sent_directory',
		'feed_outbox_directory'       => 'eb2ccore/feed/filetransfer_exports/product/local_directory',
		'feed_import_archive'         => 'eb2ccore/feed/import_archive',
		'feed_export_archive'         => 'eb2ccore/feed/export_archive',
		'feed_ack_inbox'              => 'eb2ccore/feed/filetransfer_imports/acknowledgments/local_directory',
	);
}
