<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * Add new JS to do specific giftcard functionality
 */
?>
<script type="text/javascript">
	function checkEbayEnterpriseGiftCardStatus() {
		new Ajax.Updater(
			'ebay_enterprise_giftcard_balance_lookup',
			'<?php echo Mage::getUrl('ebayenterprise_giftcard/cart/balance') ?>',
			{
				onCreate: function() { $('ebay-enterprise-giftcard-please-wait').show(); },
				onComplete: function() { $('ebay-enterprise-giftcard-please-wait').hide(); },
				parameters : {ebay_enterprise_giftcard_code : $('ebay_enterprise_giftcard_code').value, ebay_enterprise_giftcard_pin : $('ebay_enterprise_giftcard_pin').value}
			}
		);
	}

	function addEbayEnterpriseGiftCard() {
		var code = $('ebay_enterprise_giftcard_code').value;
		var pin = $('ebay_enterprise_giftcard_pin').value;
		var data = {};
		data['ebay_enterprise_giftcard_code'] = code;
		data['ebay_enterprise_giftcard_pin'] = pin;
		data['ebay_enterprise_giftcard_action'] = 'add';
		order.loadArea(['totals', 'billing_method', 'items'], true, data);
	}

	function removeEbayEnterpriseGiftCard(code) {
		var data = {};
		data['ebay_enterprise_giftcard_code'] = code;
		data['ebay_enterprise_giftcard_action'] = 'remove';
		order.loadArea(['totals', 'billing_method', 'items'], true, data);
	}
</script>
