<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Nearly identical template to:
 * app/design/frontend/base/default/template/ebayenterprise_creditcard/form/cc.phtml
 * Any fixes to this template are likely to be required there as well.
 */

/** @var EbayEnterprise_CreditCard_Block_Form_Cc $this */
$_code = $this->getMethodCode();
$_fields = $this->getFormFields();
?>
<input id="<?php echo $_fields['method'] ?>" type="hidden" name="payment[method]" value="<?php echo $_code ?>" />
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<label for="<?php echo $_fields['type'] ?>"><?php echo $this->__('Credit Card Type') ?> <em class="required">*</em></label>
		<div class="input-box">
			<select id="<?php echo $_fields['type'] ?>" name="payment[cc_type]" class="required-entry">
				<option value=""><?php echo $this->__('--Please Select--')?></option>
			<?php $_ccType = $this->getInfoData('cc_type') ?>
			<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
				<option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
			<?php endforeach ?>
			</select>
		</div>
	</li>
	<li>
		<label for="<?php echo $_fields['number'] ?>"><?php echo $this->__('Credit Card Number') ?> <em class="required">*</em></label>
		<div class="input-box">
			<?php if (!$this->getInfoData('cc_number')) : ?>
				<input type="text" id="<?php echo $_fields['number'] ?>" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" data-encrypted-name="payment[cc_number]" data-client-encrypted="false"/>
			<?php else: ?>
				<input type="hidden" id="<?php echo $_fields['number'] ?>" data-encrypted-name="payment[cc_number]" value="<?php echo $this->getInfoData('cc_number'); ?>" data-client-encrypted="true" />*********<?php echo $this->getInfoData('cc_last4'); ?>
			<?php endif; ?>
			<?php if ($this->isUsingClientSideEncryption()): ?>
				<input id="<?php echo $_fields['last_four'] ?>" type="hidden" name="payment[cc_last4]" value="<?php echo $this->getInfoData('cc_last4'); ?>" />
			<?php endif; ?>
		</div>
	</li>
	<li id="<?php echo $_code ?>_cc_type_exp_div">
		<label for="<?php echo $_fields['expiration_month'] ?>"><?php echo $this->__('Expiration Date') ?> <em class="required">*</em></label>
		<div class="input-box">
			<div class="v-fix">
				<select id="<?php echo $_fields['expiration_month'] ?>" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
				<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
				<?php foreach ($this->getCcMonths() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
			<div class="v-fix">
				<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
				<select id="<?php echo $_fields['expiration_year'] ?>" name="payment[cc_exp_year]" class="year required-entry">
				<?php foreach ($this->getCcYears() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
		</div>
	</li>
	<?php echo $this->getChildHtml() ?>
	<?php if($this->hasVerification()): ?>
	<li id="<?php echo $_code ?>_cc_type_cvv_div">
		<label for="<?php echo $_fields['cid'] ?>"><?php echo $this->__('Card Verification Number') ?> <em class="required">*</em></label>
		<div class="input-box">
			<div class="v-fix">
				<?php if (!$this->getInfoData('cc_cid')) : ?>
					<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_fields['cid'] ?>" name="payment[cc_cid]" value="" data-encrypted-name="payment[cc_cid]" data-client-encrypted="false"/>
				<?php else: ?>
					<input type="hidden" id="<?php echo $_fields['cid'] ?>" data-encrypted-name="payment[cc_cid]" value="<?php echo $this->getInfoData('cc_cid'); ?>" data-client-encrypted="true" />****
				<?php endif; ?>
			</div>
			<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
		</div>
	</li>
	<?php endif; ?>

	<?php if ($this->hasSsCardType()): ?>
	<li id="<?php echo $_code ?>_cc_type_ss_div">
		<ul class="inner-form">
			<li class="form-alt"><label for="<?php echo $_fields['issue'] ?>"><?php echo $this->__('Switch/Solo/Maestro Only') ?> <em class="required">*</em></label></li>
			<li>
				<label for="<?php echo $_fields['issue'] ?>"><?php echo $this->__('Issue Number') ?>:</label>
				<span class="input-box">
					<input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_fields['issue'] ?>" name="payment[cc_ss_issue]" value="" />
				</span>
			</li>

			<li>
				<label for="<?php echo $_fields['start_month'] ?>"><?php echo $this->__('Start Date') ?>:</label>
				<div class="input-box">
					<div class="v-fix">
						<select id="<?php echo $_fields['start_month'] ?>" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
						<?php foreach ($this->getCcMonths() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
					<div class="v-fix">
						<select id="<?php echo $_fields['start_year'] ?>" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
						<?php foreach ($this->getSsStartYears() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
				</div>
			</li>
			<li class="adv-container">&nbsp;</li>
		</ul>
	</li>
	<?php endif; ?>
</ul>
<?php if ($this->isUsingClientSideEncryption()): ?>
<script>
(function () {

var braintree = Braintree.create('<?php echo $this->getEncryptionKey() ?>');

/**
 * Update the hidden card number last 4 field with the last 4 digits of the
 * unencrypted CC number field.
 * @param Event evt
 * @param Element input
 */
function updateCardNumberLastFour(evt, input) {
	$('<?php echo $_fields["last_four"] ?>').value = input.value.replace(/\s/g, '').slice(-4);
}

/**
 * Encrypt the input field and set the value to the linked encrypted data field.
 * @param Element input
 * @return Element
 */
function encryptField(input) {
	input.retrieve('encryptedField').value = input.value ? braintree.encrypt(input.value.replace(/\s/g, '')) : '';
	return input;
}

/**
 * Callback to onChange event on fields that are to be encrypted.
 * @param Event evt
 * @param Element input
 */
function updateEncryptedField(evt, input) {
	updateField(input);
}

/**
 * Create a hidden input element to hold the encrypted data.
 * @param  Element input
 * @return Element
 */
function makeEncryptedField(input) {
	var encryptedField = new Element('input', {name: input.readAttribute('data-encrypted-name'), type: 'hidden'});
	input.insert({after: encryptedField})
		.store('encryptedField', encryptedField)
		.writeAttribute('name', false)
		.on('change', updateEncryptedField);

	updateField(input);
	return encryptedField;
}

/**
 * Determine if the passed in input is encrypted or not.
 * @param Element input
 * @param bool
 */
function isInputEncrypted(input) {
	return input.readAttribute('data-client-encrypted') == 'true';
}

/**
 * Update the passed in input field accordingly.
 * Update the encrypted input field with encrypted data only when it is not yet encrypted.
 * Otherwise use the already encrypted data to update the encrypted input field.
 * @param Element input
 * @return void
 */
function updateField(input) {
	if (!isInputEncrypted(input)) {
		encryptField(input);
	} else {
		input.retrieve('encryptedField').value = input.value;
	}
}

$$('input[data-encrypted-name]').each(makeEncryptedField);
$('<?php echo $_fields["number"] ?>').on('change', updateCardNumberLastFour);
})();
</script>
<?php endif;
