<?php
/**
 * @category   TrueAction
 * @package    TrueAction_Eb2c
 * @copyright  Copyright (c) 2013 True Action Network (http://www.trueaction.com)
 */
?>
<script type="text/javascript">
//<![CDATA[
svCheck = new svAjaxCheck('<?php echo $this->getUrl("eb2cstoredvalue/ajax/checkPan");?>');
//]]>
</script>

<fieldset class="form-list">
	<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
		<li>
			<div class="input-box">
				<label for="eb2c_sv_action_redeem"><input type="radio" id="eb2c_sv_action_redeem" name="payment[storedvalue_action]" title="<?php echo $this->__('Redeem Card') ?>" class="radio" value="Redeem Card" <?php if ($this->getAccountAction() === 'Redeem Card' || trim($this->getAccountAction()) === '') {?>checked="checked"<?php } ?> /> <?php echo $this->__('Redeem Card') ?></label>

			</div>
			<div class="input-box">
				<label for="eb2c_sv_action_balance"><input type="radio" id="eb2c_sv_action_balance" name="payment[storedvalue_action]" title="<?php echo $this->__('Check Balance') ?>" class="radio" value="Check Balance" <?php if ($this->getAccountAction() === 'Check Balance') {?>checked="checked"<?php } ?>/> <?php echo $this->__('Check Balance') ?></label>

			</div>
		</li>
		<li>
			<label for="eb2c_sv_pan" class="required"><em>*</em><?php echo $this->__('Payment Account Numbers (PAN):') ?></label>
			<div class="input-box">
				<input type="text" id="eb2c_sv_pan" name="payment[storedvalue_pan]" title="<?php echo $this->__('Payment Account Numbers') ?>" class="input-text required-entry validate-number validate-storedvalue-pan" style="display: block; float: left;" value="<?php echo $this->getAccountPan() ?>" onchange="svCheck.checkPan(this); return false;"/>
			</div>
		</li>
		<li>
			<label for="eb2c_sv_pin" class="required"><em>*</em><?php echo $this->__('Personal Identification Number (PIN):') ?></label>
			<div class="input-box">
				<input type="text" id="eb2c_sv_pin" name="payment[storedvalue_pin]" title="<?php echo $this->__('Personal Identification Number') ?>" class="input-text required-entry" value="<?php echo $this->getAccountPin() ?>" />
			</div>
		</li>
	</ul>
</fieldset>
