<?php
/**
 * @category   TrueAction
 * @package    TrueAction_Eb2c
 * @copyright  Copyright (c) 2013 True Action Network (http://www.trueaction.com)
 */
?>
<?php if ($infoData = $this->getMethod()): ?>
	<?php echo $this->htmlEscape($infoData->getTitle()) ?><br />
	<?php echo $this->__('PAN: %s', $this->htmlEscape($infoData->getAccountPan())) ?><br />
	<?php echo $this->__('PIN: %s', $this->htmlEscape($infoData->getAccountPin())) ?><br />
	<form method="post" style="display:block;">
		<fieldset class="form-list">
			<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:block">
				<input id="eb2c_sv_action" type="hidden" name="payment[storedvalue_action]" value="Void Card" />
				<input id="eb2c_sv_pan" type="hidden" name="payment[storedvalue_pan]" value="<?php echo $infoData->getAccountPan(); ?>" />
				<input id="eb2c_sv_pin" type="hidden" name="payment[storedvalue_pin]" value="<?php echo $infoData->getAccountPin(); ?>" />
				<li>
					<div class="buttons-set"><button onclick="svVoid.voidCard('<?php echo $this->getUrl("eb2cstoredvalue/ajax/voidCard");?>'); return false;" class="button btn-checkout" title="Void Redeem" type="button"><span><span>Void Redeem</span></span></button></div>
				</li>
			</ul>
		</fieldset>
	</form>
<?php endif; ?>
