#!/usr/bin/env bash

repo="$PWD"

echo 'Setting up composer'
cp "$repo/circle-ci/composer.json" .
composer --global --no-interaction config repositories.this path "$repo"
# Firegento has to come last
composer --global --no-interaction config repositories.firegento composer http://packages.firegento.com
composer --no-interaction --no-update require \
        'ebayenterprise/magento-retail-order-management:*@dev'
composer --no-interaction --prefer-source update

echo 'Removing base url from database'
mysql --user ubuntu -e 'DELETE FROM core_config_data WHERE path LIKE "web/%secure/base_url"\g' circle_test

echo 'Configuring Magento for testing'
cp "$repo"/tests/composer.xml app/etc/
cp "$repo"/tests/local.xml.phpunit.docker app/etc/local.xml.phpunit
cp "$repo"/tests/phpunit.xml.dist .
