<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<?php if ($this->canRedeem()): ?>
    <div class="account-balance">
        <h2 class="sub-title"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Redeem Gift Card'); ?></h2>
        <p><?php echo Mage::helper('enterprise_giftcardaccount')->__('Have a gift card? <a href="%s">Click here</a> to redeem it.', Mage::getUrl('enterprise_giftcardaccount/customer')); ?></p>
    </div>
<?php endif; ?>
