<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<?php $card = $this->getCard() ?>
<?php if ($card->getId()): ?>
    <div class="gift-card-info">
        <p><?php echo $this->__("Gift Card: %s", '<strong class="giftcard-number">' . $card->getCode() . '</strong>'); ?></p>
        <p><?php echo $this->__('Current Balance: %s', '<strong>' . Mage::helper('core')->currency($card->getBalance()) . '</strong>'); ?></p>
        <?php if ($card->getDateExpires()): ?>
            <p><?php echo $this->__('Expires: %s', '<strong>' . $this->formatDate($card->getDateExpires(), 'short') . '</strong>'); ?></p>
        <?php endif; ?>
    </div>
<?php else: ?>
    <p class="error-msg"><?php echo $this->__('Wrong or expired Gift Card Code.'); ?></p>
<?php endif; ?>
