<?php
/**
 * @var $this EbayEnterprise_Paypal_Block_Express_Shortcut
 */
?>
<p class="paypal-logo">
	<?php $shortcutHtmlId = $this->getShortcutHtmlId() ?>
	<?php if ($this->isOrPositionBefore()): ?>
		<span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
	<?php endif; ?>
	<a data-action="checkout-form-submit" id="<?php echo $shortcutHtmlId ?>"
	   href="<?php echo $this->getCheckoutUrl() ?>"><img
			src="<?php echo $this->getImageUrl() ?>"
			alt="<?php echo Mage::helper('ebayenterprise_paypal')->__(
				'Checkout with PayPal'
			); ?>" title="<?php echo Mage::helper('ebayenterprise_paypal')->__(
			'Checkout with PayPal'
		); ?>"/></a>
</p>
<?php if ($this->isOrPositionAfter()): ?>
	<li>
		<p class="paypal-logo">
			<span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
		</p>
	</li>
<?php endif; ?>
<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
	<?php if ($this->getIsInCatalogProduct()): ?>
		<input type="hidden" id="pp_checkout_url" name="return_url" value=""/>
	<?php endif; ?>
	<script type="text/javascript">
		//<![CDATA[
		$$('#<?php echo $shortcutHtmlId ?>').invoke('observe', 'click', function (event) {
			<?php if ($this->getConfirmationUrl()): ?>
			if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
				this.href = '<?php echo $this->getConfirmationUrl() ?>';
			}
			<?php endif; ?>
			<?php if ($this->getIsInCatalogProduct()): ?>
			$('pp_checkout_url').value = this.href;
			productAddToCartForm.submit(this);
			event.stop();
			<?php endif; ?>
		});
		//]]>
	</script>
<?php endif; ?>
