<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this EbayEnterprise_Order_Block_Order_Shipment_Tracking */ ?>
<?php $results = $this->getTrackingInfo(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Tracking Information'); ?></h1>
    <button class="button" onclick="window.close(); window.opener.focus();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
</div>

<?php if (sizeof($results) > 0): ?>
    <?php foreach ($results as $shipid => $result): ?>
        <?php if ($shipid): ?>
            <h2 class="sub-title"><?php echo $this->__('Shipment #').$shipid; ?></h2>
        <?php endif; ?>
        <?php if (sizeof($result) > 0): ?>
            <?php $rowCount = sizeof($result); $counter = 1; $id = 0; ?>
            <?php foreach ($result as $track): ?>
                <table class="tracking-table-popup data-table" id="tracking-table-popup-<?php echo $id ?>">
                    <col width="15%" />
                    <col />
                    <tbody>
                        <?php if (is_object($track)): ?>
                            <tr>
                                <th class="label"><?php echo $this->__('Tracking Number:'); ?></th>
                                <td class="value"><?php echo $this->escapeHtml($track->getTracking()); ?></td>
                            </tr>
                            <?php if ($track->getCarrierTitle()): ?>
                                <tr>
                                    <th class="label"><?php echo $this->__('Carrier:'); ?></th>
                                    <td class="value"><?php echo $this->escapeHtml($track->getCarrierTitle()); ?></td>
                                </tr>
                            <?php endif; ?>
                            <?php if ($track->getUrl()): ?>
                                <tr>
                                    <th class="label"><?php echo $this->__('Track:'); ?></th>
                                    <td class="value"><a href="<?php echo $this->escapeHtml($track->getUrl()); ?>" onclick="this.target='_blank'"><?php echo $this->escapeHtml($track->getUrl()); ?></a></td>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('tracking-table-popup-<?php echo $id++ ?>');</script>
                <div class="divider"></div>
                <?php $counter++; ?>
                <!--end for each tracking information-->
            <?php endforeach; ?>
        <?php else: ?>
            <p><?php echo $this->__('There is no tracking available for this shipment.'); ?></p>
        <?php endif; ?>
    <?php endforeach; ?>
<?php else: ?>
    <p><?php echo $this->__('There is no tracking available.'); ?></p>
<?php endif; ?>

<div class="buttons-set">
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close Window')) ?>" class="button" onclick="window.close(); window.opener.focus();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
</div>
