<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * @var Enterprise_GiftCardAccount_Block_Account_Redeem $this
 */
?>
<div class="page-title">
	<h1><?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card'); ?></h1>
</div>
<div class="giftcardaccount">
	<span id="gc-please-wait" class="please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
	</span>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form id="giftcard-form" action="<?php echo $this->getUrl('*/*/*') ?>" method="post"<?php if (!$this->canRedeem()): ?> onsubmit="giftCardAccountLookupBalance(); return false;"<?php endif; ?>>
		<div id="giftcard_balance_lookup"></div>
		<div class="fieldset">
			<ul class="form-list">
				<li>
					<label for="giftcard_code" class="required"><em>*</em><?php echo $this->__('Payment Account Numbers (PAN)') ?></label>
					<input type="text" class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" />
				</li>
				<li>
					<label for="giftcard_pin" class="required"><em>*</em><?php echo $this->__('Personal Identification Number (PIN)') ?></label>
					<input type="text" class="required-entry input-text" id="giftcard_pin" name="giftcard_pin" value="" />
				</li>
			</ul>
		</div>
		<div class="buttons-set form-buttons btn-only">
<?php if ($this->canRedeem()): ?>
			<button class="button" onclick="giftcardForm.submit()" type="button" value="<?php echo $this->__('Redeem Gift Card') ?>"><span><span><?php echo $this->__('Redeem Gift Card') ?></span></span></button>
<?php endif; ?>
			<button class="button check-gc-status" id="gca_balance_button" type="button" value="<?php echo $this->__('Check status and balance') ?>"><span><span><?php echo $this->__('Check status and balance') ?></span></span></button>
		</div>
	</form>
	<script type="text/javascript">
	//<![CDATA[
	var giftcardForm = new VarienForm('giftcard-form');
	function giftCardAccountLookupBalance() {
		if (giftcardForm.validator && !giftcardForm.validator.validate()) {
			return false;
		}
		new Ajax.Updater('giftcard_balance_lookup', '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck', array('_secure' => true)) ?>', {
			onCreate: function() {
				$('gc-please-wait').show()
				$('giftcard_balance_lookup').hide();
			},
			onComplete: function() {
				$('gc-please-wait').hide();
				$('giftcard_balance_lookup').show();
			},
			parameters : {giftcard_code : $('giftcard_code').value, giftcard_pin : $('giftcard_pin').value}
		});
	}
	$('gca_balance_button').observe('click', giftCardAccountLookupBalance);
	//]]>
	</script>
</div>
